"""Auth endpoints — registration, provisioning, impersonation exchange."""
from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from uuid import UUID
from jose import jwt, JWTError

from app.core.config import settings
from app.core.database import get_db
from app.core.security import get_current_user
from app.core.rate_limit import limiter, RATE_AUTH
from app.models.user import User
from app.models.organization import Organization, OrgMember

import logging
logger = logging.getLogger(__name__)

router = APIRouter()


class RegisterRequest(BaseModel):
    full_name: str = ""
    company_name: str = ""


@router.post("/register")
async def register_user(
    req: RegisterRequest,
    current_user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Provision user + org after Supabase signup.
    Called by frontend right after supabase.auth.signUp().
    The JWT is already valid at this point.
    """
    user_id = UUID(current_user["user_id"])
    email = current_user.get("email", "")

    # Check if user already exists in DB
    existing = await db.execute(select(User).where(User.id == user_id))
    if existing.scalar_one_or_none():
        return {"status": "already_exists", "message": "User already provisioned"}

    # Create organization
    slug = (req.company_name or email.split("@")[0]).lower().replace(" ", "-")[:100]
    # Ensure unique slug
    slug_check = await db.execute(select(Organization).where(Organization.slug == slug))
    if slug_check.scalar_one_or_none():
        slug = f"{slug}-{str(user_id)[:8]}"

    org = Organization(
        name=req.company_name or f"Org de {req.full_name}",
        slug=slug,
        plan="starter",
        max_users=1,
        max_leads=100,
        is_active=True,
    )
    db.add(org)
    await db.flush()

    # Create user record
    user = User(
        id=user_id,
        email=email,
        full_name=req.full_name,
        role="admin",
        is_active=True,
    )
    db.add(user)
    await db.flush()

    # Create org membership
    member = OrgMember(
        org_id=org.id,
        user_id=user_id,
        role="admin",
    )
    db.add(member)

    await db.commit()
    logger.info(f"Provisioned user={email} org={org.slug} plan=starter")

    # Send welcome email (fire-and-forget)
    try:
        from app.services.email_service import EmailService
        email_svc = EmailService(db)
        await email_svc.send_welcome_email(email, req.full_name)
    except Exception as e:
        logger.warning(f"Welcome email failed for {email}: {e}")

    return {
        "status": "created",
        "org_id": str(org.id),
        "org_slug": org.slug,
        "plan": "starter",
    }


# ─── Impersonation token exchange ────────────────────────────────
# Used by frontend PrivateRoute to exchange a short-lived impersonation
# token (generated by /admin/impersonate/{org_id}/login) for a real session.
# The token is verified server-side, single-use is tracked in-memory,
# and the action is audited.

class ImpersonateExchangeRequest(BaseModel):
    token: str


_used_impersonate_jti: set[str] = set()  # In-memory single-use tracking (reset on restart)


@router.post("/verify-impersonate")
@limiter.limit(RATE_AUTH)
async def verify_impersonate(
    request: Request,
    body: ImpersonateExchangeRequest,
    db: AsyncSession = Depends(get_db),
):
    """Verify an impersonation token and return a Supabase-compatible session.

    The token is a short-lived JWT (15 min) signed with the app SECRET_KEY,
    issued by an admin via /admin/impersonate/{org_id}/login.
    Each token can only be exchanged once (in-memory tracking).
    """
    try:
        payload = jwt.decode(
            body.token,
            settings.SECRET_KEY,
            algorithms=[settings.ALGORITHM],
        )
    except JWTError as e:
        logger.warning(f"Invalid impersonation token: {e}")
        raise HTTPException(status_code=401, detail="Invalid or expired impersonation token")

    # Required fields
    user_id = payload.get("sub")
    impersonated_by = payload.get("impersonated_by")
    org_id = payload.get("org_id")
    if not user_id or not impersonated_by or not org_id:
        raise HTTPException(status_code=400, detail="Malformed impersonation token")

    # Single-use enforcement (jti = hash of token)
    import hashlib
    jti = hashlib.sha256(body.token.encode()).hexdigest()
    if jti in _used_impersonate_jti:
        logger.warning(f"Replay attempt on impersonation token by {request.client.host if request.client else '?'}")
        raise HTTPException(status_code=401, detail="Impersonation token already used")
    _used_impersonate_jti.add(jti)
    # Cap memory growth — drop oldest entries if set gets too large
    if len(_used_impersonate_jti) > 1000:
        _used_impersonate_jti.clear()

    # Verify user still exists
    user = await db.get(User, UUID(user_id))
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    logger.warning(
        f"Impersonation exchange: admin={impersonated_by} → user={user.email} org={org_id} "
        f"ip={request.client.host if request.client else '?'}"
    )

    # Return a session-shaped response. The frontend passes this to supabase.auth.setSession().
    # Note: this is a backend-issued token, not a Supabase token. The session works because
    # supabase-js will accept it as the access_token for subsequent calls (the backend
    # validates it via get_current_user, not Supabase).
    return {
        "access_token": body.token,
        "refresh_token": "",
        "user_id": user_id,
        "email": user.email,
        "org_id": org_id,
        "expires_in": 900,
    }
